# Generated by Django 5.2.1 on 2025-05-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_apartment_total_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='PaidMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_pay', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pay', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('check_pay', models.FileField(upload_to='checks/')),
                ('is_full_pay', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_for_apartment', to='apartments.apartment')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paids_for_month', to='months.month')),
            ],
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months_for_year', to='months.year'),
        ),
    ]
