# Generated by Django 5.2.1 on 2025-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
