# Generated by Django 5.2.1 on 2025-05-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_apartment_options_alter_entrance_options_and_more'),
        ('months', '0002_alter_month_month_alter_year_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяца'},
        ),
        migrations.AlterModelOptions(
            name='paidmonth',
            options={'verbose_name': 'Оплата месяца', 'verbose_name_plural': 'Оплата месяцов'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'Год', 'verbose_name_plural': 'Года'},
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.PositiveSmallIntegerField(help_text='Введите номер месяца (например: 5, 9, 12)', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.ForeignKey(help_text='Выберите год', on_delete=django.db.models.deletion.CASCADE, related_name='months_for_year', to='months.year', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='apartment',
            field=models.ForeignKey(help_text='Выберите квартиру', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_for_apartment', to='apartments.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='check_pay',
            field=models.FileField(upload_to='checks/', verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='how_much_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сколько нужно оплатить'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='is_full_pay',
            field=models.BooleanField(default=False, verbose_name='Статус полной оплаты'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='month',
            field=models.ForeignKey(help_text='Выберите Месяц', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paids_for_month', to='months.month', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='paidmonth',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сколько оплатил'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Введите год (например: 2030)', verbose_name='Год'),
        ),
    ]
