# Generated by Django 5.2.1 on 2025-06-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0003_alter_month_options_alter_paidmonth_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidmonth',
            name='check_pay',
            field=models.FileField(blank=True, null=True, upload_to='checks/', verbose_name='Чек'),
        ),
    ]
