# Generated by Django 5.2.1 on 2025-05-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=4)),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_apartments_for', to='apartments.entrance')),
            ],
        ),
    ]
