# Generated by Django 5.2.1 on 2025-05-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_total_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='entrance',
            options={'verbose_name': 'Подъезд', 'verbose_name_plural': 'Подъезды'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(help_text='Введите номер квартиры', max_length=4, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='entrance',
            field=models.ForeignKey(help_text='Выберите подъезд', on_delete=django.db.models.deletion.CASCADE, related_name='entrance_apartments_for', to='apartments.entrance', verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_area',
            field=models.FloatField(default=0, help_text='Введите общую площадь квартиры (пример: 59.69)', verbose_name='Общая площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='entrance_number',
            field=models.CharField(help_text='Введите номер подъезда', max_length=4, verbose_name='Номер подъезда'),
        ),
    ]
